[package]
name = "FirstGame-flappy-Xheng1934"
version = "0.1.0"
edition = "2021"
authors = ["Xheng1934"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8"